### ISSUE TITLE
IOError: Config file not found: ./config.json

### ISSUE THREAD

**Issue by Pablohn26** [ingrammicro/fallball-connector#2]
When using docker compose option, the build works but once the container starts it raises next error

```
connector_1  | Traceback (most recent call last):
connector_1  |   File "app.py", line 9, in <module>
connector_1  |     from connector.v1 import api_bp as api_v1
connector_1  |   File "/connector/v1/__init__.py", line 13, in <module>
connector_1  |     from connector.fbclient.reseller import Reseller
connector_1  |   File "/connector/fbclient/__init__.py", line 8, in <module>
connector_1  |     config = Config()
connector_1  |   File "/connector/config.py", line 34, in __init__
connector_1  |     self.load()
connector_1  |   File "/connector/config.py", line 39, in load
connector_1  |     raise IOError("Config file not found: {}".format(Config.conf_file))
connector_1  | IOError: Config file not found: ./config.json
```

it seems it is not getting the config.json file (because it is not in that path)

**Comment by Pablohn26** [comment]
I have provided two ways to fix this problem.
The first one is to change the code and the second one is to fix the instructions.
