### ISSUE TITLE
unable to create container using docker 

### ISSUE THREAD

**Issue by RajuTanti** [ingrammicro/fallball-connector#8]
devopsdesk@devopsdesk:~/fallball_aps/fallball-connector-master$ sudo docker build -t fallball .
[sudo] password for devopsdesk:
Sending build context to Docker daemon 169.5 kB
Step 1/12 : FROM python:3.6
3.6: Pulling from library/python
f49cf87b52c1: Already exists
7b491c575b06: Already exists
b313b08bab3b: Already exists
51d6678c3f0e: Already exists
09f35bd58db2: Already exists
0f9de702e222: Pull complete
73911d37fcde: Pull complete
99a87e214c92: Pull complete
Digest: sha256:167e56eb61496b697dd58a9ebb158e4e3be065555a8fc44fd0374da861e2195e
Status: Downloaded newer image for python:3.6
 ---> c1e459c00dc3
Step 2/12 : ADD ./connector /connector
 ---> f495936a071c
Removing intermediate container 3e071d1639f0
Step 3/12 : ADD ./requirements.txt /connector/requirements.txt
 ---> f6d1e07bafad
Removing intermediate container 9dd849d27432
Step 4/12 : WORKDIR /connector
 ---> b9fdba5f9d81
Removing intermediate container 8df5ffd970fe
Step 5/12 : ENV PYTHONPATH /
 ---> Running in dc7beda86363
 ---> 38892bb3f56c
Removing intermediate container dc7beda86363
Step 6/12 : ENV CONNECTOR_PORT 80
 ---> Running in 05786b29c3b1
 ---> 619358ae132d
Removing intermediate container 05786b29c3b1
Step 7/12 : ENV DEBUG True
 ---> Running in fa9a286ee981
 ---> a047066a4e6b
Removing intermediate container fa9a286ee981
Step 8/12 : RUN pip install -r requirements.txt
 ---> Running in 96c0d3d02915
Collecting Faker==0.7.3 (from -r requirements.txt (line 1))
  Downloading Faker-0.7.3-py2.py3-none-any.whl (529kB)
Collecting Flask==0.12 (from -r requirements.txt (line 2))
  Downloading Flask-0.12-py2.py3-none-any.whl (82kB)
Collecting requests==2.3.0 (from -r requirements.txt (line 3))
  Downloading requests-2.3.0-py2.py3-none-any.whl (452kB)
Collecting oauthlib==2.0.0 (from -r requirements.txt (line 4))
  Downloading oauthlib-2.0.0.tar.gz (122kB)
Collecting requests_oauthlib==0.6.1 (from -r requirements.txt (line 5))
  Downloading requests_oauthlib-0.6.1-py2.py3-none-any.whl
Collecting Flask-RESTful==0.3.5 (from -r requirements.txt (line 6))
  Downloading Flask_RESTful-0.3.5-py2.py3-none-any.whl
Collecting marshmallow==2.10.3 (from -r requirements.txt (line 7))
  Downloading marshmallow-2.10.3-py2.py3-none-any.whl (44kB)
Collecting slumber==0.7.1 (from -r requirements.txt (line 8))
  Downloading slumber-0.7.1.tar.gz
Collecting PyYAML==3.12 (from -r requirements.txt (line 9))
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting six (from Faker==0.7.3->-r requirements.txt (line 1))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.4 (from Faker==0.7.3->-r requirements.txt (line 1))
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
Collecting Werkzeug>=0.7 (from Flask==0.12->-r requirements.txt (line 2))
  Downloading Werkzeug-0.13-py2.py3-none-any.whl (311kB)
Collecting click>=2.0 (from Flask==0.12->-r requirements.txt (line 2))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting Jinja2>=2.4 (from Flask==0.12->-r requirements.txt (line 2))
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)
Collecting itsdangerous>=0.21 (from Flask==0.12->-r requirements.txt (line 2))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting pytz (from Flask-RESTful==0.3.5->-r requirements.txt (line 6))
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
Collecting aniso8601>=0.82 (from Flask-RESTful==0.3.5->-r requirements.txt (line 6))
  Downloading aniso8601-1.3.0.tar.gz (57kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask==0.12->-r requirements.txt (line 2))
  Downloading MarkupSafe-1.0.tar.gz
Building wheels for collected packages: oauthlib, slumber, PyYAML, itsdangerous, aniso8601, MarkupSafe
  Running setup.py bdist_wheel for oauthlib: started
  Running setup.py bdist_wheel for oauthlib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e4/e1/92/68af4b20ac26182fbd623647af92118fc4cdbdb2c613030a67
  Running setup.py bdist_wheel for slumber: started
  Running setup.py bdist_wheel for slumber: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ad/a7/f9/37bd9ef126d9733705ab4c1fd3c1cd07ff49917579df9fdda2
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for itsdangerous: started
  Running setup.py bdist_wheel for itsdangerous: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for aniso8601: started
  Running setup.py bdist_wheel for aniso8601: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e3/6a/48/e4f2d89ff4146557cae20b77a9af7b4d09dd47b2004133cd7e
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built oauthlib slumber PyYAML itsdangerous aniso8601 MarkupSafe
Installing collected packages: six, python-dateutil, Faker, Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, Flask, requests, oauthlib, requests-oauthlib, pytz, aniso8601, Flask-RESTful, marshmallow, slumber, PyYAML
Successfully installed Faker-0.7.3 Flask-0.12 Flask-RESTful-0.3.5 Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.12 Werkzeug-0.13 aniso8601-1.3.0 click-6.7 itsdangerous-0.24 marshmallow-2.10.3 oauthlib-2.0.0 python-dateutil-2.6.1 pytz-2017.3 requests-2.3.0 requests-oauthlib-0.6.1 six-1.11.0 slumber-0.7.1
 ---> b8f9da5718d1
Removing intermediate container 96c0d3d02915
Step 9/12 : RUN pip install gunicorn
 ---> Running in cee2b965d868
Collecting gunicorn
  Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111kB)
Installing collected packages: gunicorn
Successfully installed gunicorn-19.7.1
 ---> 107ac7d106ae
Removing intermediate container cee2b965d868
Step 10/12 : EXPOSE 80
 ---> Running in 2040eb3e3c81
 ---> 3553bde12670
Removing intermediate container 2040eb3e3c81
Step 11/12 : ENTRYPOINT /usr/local/bin/gunicorn connector.app:app
 ---> Running in 826fe13a8317
 ---> 43618c17e1cd
Removing intermediate container 826fe13a8317
Step 12/12 : CMD -b 0.0.0.0:80 -t 180 -w 4 -k gthread --threads 8
 ---> Running in 957a1fc2b681
 ---> 57b6828b4e54
Removing intermediate container 957a1fc2b681
Successfully built 57b6828b4e54
devopsdesk@devopsdesk:~/fallball_aps/fallball-connector-master$ sudo docker run 57b6828b4e54
[2017-12-21 11:52:48 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2017-12-21 11:52:48 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2017-12-21 11:52:48 +0000] [1] [INFO] Using worker: gthread
[2017-12-21 11:52:48 +0000] [8] [INFO] Booting worker with pid: 8
[2017-12-21 11:52:48 +0000] [9] [INFO] Booting worker with pid: 9
[2017-12-21 11:52:48 +0000] [10] [INFO] Booting worker with pid: 10
[2017-12-21 11:52:48 +0000] [11] [INFO] Booting worker with pid: 11
[2017-12-21 11:52:50 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/connector/app.py", line 10, in <module>
    from connector.v1 import api_bp as api_v1
  File "/connector/v1/__init__.py", line 14, in <module>
    from connector.fbclient.reseller import Reseller
  File "/connector/fbclient/__init__.py", line 13, in <module>
    config = Config()
  File "/connector/config.py", line 44, in __init__
    self.load()
  File "/connector/config.py", line 49, in load
    raise IOError("Config file not found: {}".format(Config.conf_file))
OSError: Config file not found: ./config.yml
[2017-12-21 11:52:50 +0000] [9] [INFO] Worker exiting (pid: 9)
[2017-12-21 11:52:50 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/connector/app.py", line 10, in <module>
    from connector.v1 import api_bp as api_v1
  File "/connector/v1/__init__.py", line 14, in <module>
    from connector.fbclient.reseller import Reseller
  File "/connector/fbclient/__init__.py", line 13, in <module>
    config = Config()
  File "/connector/config.py", line 44, in __init__
    self.load()
  File "/connector/config.py", line 49, in load
    raise IOError("Config file not found: {}".format(Config.conf_file))
OSError: Config file not found: ./config.yml
[2017-12-21 11:52:50 +0000] [8] [INFO] Worker exiting (pid: 8)
[2017-12-21 11:52:50 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/connector/app.py", line 10, in <module>
    from connector.v1 import api_bp as api_v1
  File "/connector/v1/__init__.py", line 14, in <module>
    from connector.fbclient.reseller import Reseller
  File "/connector/fbclient/__init__.py", line 13, in <module>
    config = Config()
  File "/connector/config.py", line 44, in __init__
    self.load()
  File "/connector/config.py", line 49, in load
    raise IOError("Config file not found: {}".format(Config.conf_file))
OSError: Config file not found: ./config.yml
[2017-12-21 11:52:50 +0000] [11] [INFO] Worker exiting (pid: 11)
[2017-12-21 11:52:50 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/connector/app.py", line 10, in <module>
    from connector.v1 import api_bp as api_v1
  File "/connector/v1/__init__.py", line 14, in <module>
    from connector.fbclient.reseller import Reseller
  File "/connector/fbclient/__init__.py", line 13, in <module>
    config = Config()
  File "/connector/config.py", line 44, in __init__
    self.load()
  File "/connector/config.py", line 49, in load
    raise IOError("Config file not found: {}".format(Config.conf_file))
OSError: Config file not found: ./config.yml
[2017-12-21 11:52:50 +0000] [10] [INFO] Worker exiting (pid: 10)
[2017-12-21 11:52:50 +0000] [1] [INFO] Shutting down: Master
[2017-12-21 11:52:50 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by themaxbelov** [comment]
Use docker-compose:
https://github.com/ingrammicro/fallball-connector#running-in-docker

Or copy the config file / mount volume with config file to /connector folder inside container.
